AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  work:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      Runtime: python3.6
      FunctionName: leech-work
      VpcConfig:
        SecurityGroupIds:
          - sg-06b3a26ff04155688
        SubnetIds:
          - subnet-872a24cc
          - subnet-29497e4d
          - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
  monitor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      Runtime: python3.6
      FunctionName: leech-monitor
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
      ReservedConcurrentExecutions: 100
  extract:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-extract
      VpcConfig:
        SecurityGroupIds:
          - sg-06b3a26ff04155688
        SubnetIds:
          - subnet-872a24cc
          - subnet-29497e4d
          - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Events:
        extraction:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:extraction
            BatchSize: 1
      Tracing: Active
      ReservedConcurrentExecutions: 100
  transform:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-transform
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Events:
        transformation:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:transform
            BatchSize: 1
      Tracing: Active
      ReservedConcurrentExecutions: 100
  assimilate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-assimilate
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Events:
        assimilation:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:assimilate
            BatchSize: 1
      Tracing: Active
      ReservedConcurrentExecutions: 100
  load:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-load
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Events:
        loading:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:load
            BatchSize: 1
      Tracing: Active
      ReservedConcurrentExecutions: 100
  audit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-audit
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
  aphid:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.aphid
      Runtime: python3.6
      FunctionName: leech-aphid
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
