AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members

Resources:
  work:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      Runtime: python3.6
      FunctionName: leech-work
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
  monitor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      Runtime: python3.6
      FunctionName: leech-monitor
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 60
      MemorySize: 448
      Tracing: Active
      Environment:
        Variables:
          WORK_FUNCTION: leech-work
          SCHEMA_TABLE: Schema
          EXTRACTION_URL: https://sqs.us-east-1.amazonaws.com/803040539655/extraction
  monitor-object:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-monitor
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Events:
        monitor:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:monitor
            BatchSize: 10
      Tracing: Active
      Environment:
        Variables:
          WORK_FUNCTION: leech-work
          SCHEMA_TABLE: Schema
          TRANSFORM_URL: https://sqs.us-east-1.amazonaws.com/803040539655/transform
          LINK_URL: https://sqs.us-east-1.amazonaws.com/803040539655/link
  extract:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-extract
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 60
      MemorySize: 448
      Events:
        extraction:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:extraction
            BatchSize: 10
      Tracing: Active
      Environment:
        Variables:
          WORK_FUNCTION: leech-work
          SCHEMA_TABLE: Schema
          TRANSFORM_URL: https://sqs.us-east-1.amazonaws.com/803040539655/transform
  transform:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-transform
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 120
      MemorySize: 448
      Events:
        transformation:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:transform
            BatchSize: 10
      Tracing: Active
      Environment:
        Variables:
          WORK_FUNCTION: leech-work
          SCHEMA_TABLE: Schema
  assimilate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-assimilate
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 120
      MemorySize: 448
      Events:
        assimilation:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:assimilate
            BatchSize: 10
      Tracing: Active
      Environment:
        Variables:
          WORK_FUNCTION: leech-work
          SCHEMA_TABLE: Schema
  load:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-load
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Events:
        loading:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:load
            BatchSize: 10
      Tracing: Active
      Environment:
        Variables:
          NEPTUNE_ENDPOINT: algernon.cluster-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com
          GRAPH_READER_ENDPOINT: algernon.cluster-ro-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com
  audit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      Runtime: python3.6
      FunctionName: leech-audit
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
  aphid:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.aphid
      Runtime: python3.6
      FunctionName: leech-aphid
      VpcConfig:
        SecurityGroupIds:
        - sg-06b3a26ff04155688
        SubnetIds:
        - subnet-872a24cc
        - subnet-29497e4d
        - subnet-acef95f1
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
      Environment:
        Variables:
          NEPTUNE_ENDPOINT: algernon.cluster-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com
          GRAPH_READER_ENDPOINT: algernon.cluster-ro-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com
  explode:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.exploded
      Runtime: python3.6
      FunctionName: leech-explode
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
  log:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/log_process.handler
      Runtime: python3.6
      FunctionName: leech-process-log
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 128
      Tracing: Active
  credibleWsExtractor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/credible_ws.handler
      Runtime: python3.6
      FunctionName: leech-extract-crediblews
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
  credibleFeExtractor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/credible_fe.handler
      Runtime: python3.6
      FunctionName: leech-extract-crediblefe
      Role: arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE
      Timeout: 300
      MemorySize: 448
      Tracing: Active
