AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  LeechVpcSg:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: List of security groups the Leech will use to access the data space
    Default: "sg-06b3a26ff04155688"
  LeechVpcSn:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet ids that the Leech can launch into to access the data space
    Default: "subnet-872a24cc, subnet-29497e4d, subnet-acef95f1"
  LambdaRoleArn:
    Type: String
    Description: The ARN of the IAM role that lambda functions will use to interact with the resources
    Default: "arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE"

Globals:
  Function:
    Runtime: python3.6
    Layers:
      - "arn:aws:lambda:us-east-1:803040539655:layer:leechLayer:7"
    Tracing: Active
    Environment:
      Variables:
        WORK_FUNCTION: leech-work
        SCHEMA_TABLE: Schema
        EXTRACTION_URL: https://sqs.us-east-1.amazonaws.com/803040539655/extraction
        TRANSFORM_URL: https://sqs.us-east-1.amazonaws.com/803040539655/transform
        ASSIMILATE_URL: https://sqs.us-east-1.amazonaws.com/803040539655/assimilate
        LOAD_URL:  https://sqs.us-east-1.amazonaws.com/803040539655/load
        LINK_URL: https://sqs.us-east-1.amazonaws.com/803040539655/link
        GRAPH_DB_ENDPOINT: algernon.cluster-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com
        GRAPH_DB_READER_ENDPOINT: algernon.cluster-ro-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com

Resources:
  work:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      FunctionName: leech-work
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  decide:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/ruffians.decide
      FunctionName: leech-decide
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  labor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/ruffians.labor
      FunctionName: leech-labor
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  lambdaLabor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/ruffians.lambda_labor
      FunctionName: leech-lambda-labor
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  vpclabor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/ruffians.lambda_labor
      FunctionName: leech-vpc-labor
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448
      VpcConfig:
        SecurityGroupIds:
          Ref: LeechVpcSg
        SubnetIds:
          Ref: LeechVpcSn

  aphid:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.aphid
      FunctionName: leech-aphid
      Role:
        Ref: LambdaRoleArn
      VpcConfig:
        SecurityGroupIds:
          Ref: LeechVpcSg
        SubnetIds:
          Ref: LeechVpcSn
      Timeout: 300
      MemorySize: 448

  log:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/log_process.handler
      FunctionName: leech-process-log
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 128

  credibleWsExtractor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/credible_ws.handler
      FunctionName: leech-extract-crediblews
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  credibleFeExtractor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/credible_fe.handler
      FunctionName: leech-extract-crediblefe
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448
