AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  LeechVpcSg:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: List of security groups the Leech will use to access the data space
    Default: "sg-06b3a26ff04155688"
  LeechVpcSn:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet ids that the Leech can launch into to access the data space
    Default: "subnet-872a24cc, subnet-29497e4d, subnet-acef95f1"
  LambdaRoleArn:
    Type: String
    Description: The ARN of the IAM role that lambda functions will use to interact with the resources
    Default: "arn:aws:iam::803040539655:role/midnightRed-graphWorkerRole-1KSOKSCZ2OLZE"

Globals:
  Function:
    Runtime: python3.6
    Layers:
      - "arn:aws:lambda:us-east-1:803040539655:layer:leechLayer:2"
    Tracing: Active
    Environment:
      Variables:
        WORK_FUNCTION: leech-work
        SCHEMA_TABLE: Schema
        EXTRACTION_URL: https://sqs.us-east-1.amazonaws.com/803040539655/extraction
        TRANSFORM_URL: https://sqs.us-east-1.amazonaws.com/803040539655/transform
        ASSIMILATE_URL: https://sqs.us-east-1.amazonaws.com/803040539655/assimilate
        LOAD_URL:  https://sqs.us-east-1.amazonaws.com/803040539655/load
        LINK_URL: https://sqs.us-east-1.amazonaws.com/803040539655/link
        NEPTUNE_ENDPOINT: algernon.cluster-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com
        GRAPH_READER_ENDPOINT: algernon.cluster-ro-cnv3iqiknsnm.us-east-1.neptune.amazonaws.com

Resources:
  work:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      FunctionName: leech-work
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  monitor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.work
      FunctionName: leech-monitor
      Role:
        Ref: LambdaRoleArn
      Timeout: 60
      MemorySize: 448

  monitorObject:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      FunctionName: leech-monitor-object
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448
      Events:
        monitor:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:monitor
            BatchSize: 10

  extract:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      FunctionName: leech-extract
      Role:
        Ref: LambdaRoleArn
      Timeout: 60
      MemorySize: 448
      Events:
        extraction:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:extraction
            BatchSize: 10

  transform:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      FunctionName: leech-transform
      Role:
        Ref: LambdaRoleArn
      Timeout: 120
      MemorySize: 448
      Events:
        transformation:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:transform
            BatchSize: 10

  assimilate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      FunctionName: leech-assimilate
      Role:
        Ref: LambdaRoleArn
      Timeout: 120
      MemorySize: 448
      Events:
        assimilation:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:assimilate
            BatchSize: 10

  load:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      FunctionName: leech-load
      Role:
        Ref: LambdaRoleArn
      VpcConfig:
        SecurityGroupIds:
          Ref: LeechVpcSg
        SubnetIds:
          Ref: LeechVpcSn
      Timeout: 300
      MemorySize: 448
      Events:
        loading:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:803040539655:load
            BatchSize: 10

  audit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.queued
      FunctionName: leech-audit
      Role:
        Ref: LambdaRoleArn
      VpcConfig:
        SecurityGroupIds:
          Ref: LeechVpcSg
        SubnetIds:
          Ref: LeechVpcSn
      Timeout: 300
      MemorySize: 448

  aphid:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.aphid
      FunctionName: leech-aphid
      Role:
        Ref: LambdaRoleArn
      VpcConfig:
        SecurityGroupIds:
          Ref: LeechVpcSg
        SubnetIds:
          Ref: LeechVpcSn
      Timeout: 300
      MemorySize: 448

  explode:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/toll_booth.exploded
      FunctionName: leech-explode
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  log:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/log_process.handler
      FunctionName: leech-process-log
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 128

  credibleWsExtractor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/credible_ws.handler
      FunctionName: leech-extract-crediblews
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  credibleFeExtractor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/credible_fe.handler
      FunctionName: leech-extract-crediblefe
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  propagate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/toll_booth.propagate
      FunctionName: leech-propagate
      Role:
        Ref: LambdaRoleArn
      Timeout: 300
      MemorySize: 448

  fruit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: toll_booth/alg_tasks/extractors/toll_booth.fruit
      FunctionName: leech-fruit
      Role:
        Ref: LambdaRoleArn
      Timeout: 600
      MemorySize: 448
