import json
import os

import bs4

from toll_booth.alg_obj.graph.ogm.regulators import IdentifierStem

test_html = '''
<select name="changelogtype_id" style="width:400px" id="changelogtype_id" size="1">
<option value=""> -- Action Type -- </option>
<option value="386"></option>
<option value="387">?Client Amendment Deleted</option>
<option value="657">ACCEPT CLIENT PRESCRIPTION CHANGE REQUEST(G)</option>
<option value="659">ACCEPT CLIENT PRESCRIPTION CHANGE REQUEST(P)</option>
<option value="658">ACCEPT CLIENT PRESCRIPTION CHANGE REQUEST(T)</option>
<option value="133">ACCEPT REFILL REQUEST</option>
<option value="661">ACCEPTwEDITS CLIENT PRESCRIPTION CHANGE REQUEST(G)</option>
<option value="660">ACCEPTwEDITS CLIENT PRESCRIPTION CHANGE REQUEST(T)</option>
<option value="583">ACCESS 277 ACKNOWLEDGEMENT LIST</option>
<option value="584">ACCESS 277 ERROR PAGE</option>
<option value="585">ACCESS 277 VIEW PAGE</option>
<option value="577">ACCESS 999 ACKNOWLEDGMENT LIST</option>
<option value="578">ACCESS 999 ERROR PAGE</option>
<option value="579">ACCESS 999 VIEW PAGE</option>
<option value="361">ACCESS ADMIN PAGE</option>
<option value="530">ACCESS BILLING GROUPS PAGE</option>
<option value="362">ACCESS BILLING PAGE</option>
<option value="319">ACCESS CLIENT ADVANCED SEARCH</option>
<option value="2">ACCESS CLIENT DOWNLOAD</option>
<option value="93">ACCESS CLIENT EXT RECORD</option>
<option value="357">ACCESS CLIENT PAGE</option>
<option value="652">ACCESS CLIENT PORTAL CLIENT ACCESS KEYS</option>
<option value="541">ACCESS CLIENT PORTAL VISIT</option>
<option value="80">ACCESS CLIENT PRINTABLE RECORD</option>
<option value="1">ACCESS CLIENT RECORD</option>
<option value="380">ACCESS CLIENT SCHEDULE PAGE - DAY</option>
<option value="379">ACCESS CLIENT SCHEDULE PAGE - MONTH</option>
<option value="378">ACCESS CLIENT SCHEDULE PAGE - WEEK</option>
<option value="35">ACCESS CLIENT VISIT</option>
<option value="331">ACCESS CLIENT VISIT TEMPLATE</option>
<option value="447">ACCESS CLINICAL SUMMARY GENERATOR</option>
<option value="448">ACCESS CLINICAL SUMMARY GENERATOR (CLIENT)</option>
<option value="349">ACCESS EMPLOYEE ADVANCED SEARCH</option>
<option value="72">ACCESS EMPLOYEE FORM</option>
<option value="358">ACCESS EMPLOYEE PAGE</option>
<option value="375">ACCESS EMPLOYEE SCHEDULE PAGE - DAY</option>
<option value="376">ACCESS EMPLOYEE SCHEDULE PAGE - MONTH</option>
<option value="377">ACCESS EMPLOYEE SCHEDULE PAGE - WEEK</option>
<option value="338">ACCESS EXPORT</option>
<option value="364">ACCESS FORMS PAGE</option>
<option value="365">ACCESS FUNDS PAGE</option>
<option value="356">ACCESS HOME PAGE</option>
<option value="525">ACCESS INPATIENT PAGE</option>
<option value="351">ACCESS LEDGER ADVANCED SEARCH</option>
<option value="582">ACCESS LOAD 277 PAGE</option>
<option value="449">ACCESS MANAGEDCARE PAGE</option>
<option value="62">ACCESS PLANNER DOWNLOAD</option>
<option value="337">ACCESS REPORT</option>
<option value="363">ACCESS REPORTS PAGE</option>
<option value="359">ACCESS SCHEDULE PAGE</option>
<option value="381">ACCESS TEAM SCHEDULE PAGE</option>
<option value="350">ACCESS VISIT ADVANCED SEARCH</option>
<option value="360">ACCESS VISIT PAGE</option>
<option value="682">ADD BILLING PAYER CONTRACT</option>
<option value="676">ADD BILLING PAYER FILE ATTACHMENT</option>
<option value="680">ADD BILLING PAYER NOTE</option>
<option value="620">ADD CLIENT CREDIBLE PLAN</option>
<option value="630">ADD CLIENT ENROLLMENT</option>
<option value="353">ADD CLIENT PAGE</option>
<option value="452">ADD CLIENT PAYMENT</option>
<option value="687">ADD CLIENT PAYMENT PLAN</option>
<option value="320">ADD CLIENT TO ATTENDANCE GROUP</option>
<option value="602">ADD CREDIBLE PLAN CUSTOM ELEMENT</option>
<option value="607">ADD CREDIBLE PLAN DISCIPLINE</option>
<option value="596">ADD CREDIBLE PLAN ELEMENT LOOKUP</option>
<option value="599">ADD CREDIBLE PLAN EXTENDED FIELD</option>
<option value="590">ADD CREDIBLE PLAN GOAL ACHIEVEMENT STATUS</option>
<option value="593">ADD CREDIBLE PLAN PRIORITY LEVEL</option>
<option value="636">ADD CREDIBLE PLAN RULE SET</option>
<option value="613">ADD CREDIBLE PLAN TEMPLATE</option>
<option value="610">ADD CREDIBLE PLAN TYPE</option>
<option value="134">ADD CREDIBLE RX PRESCRIBER</option>
<option value="354">ADD EMPLOYEE PAGE</option>
<option value="665">ADD LINKED ACCOUNT</option>
<option value="692">ADD PAYMENT PLAN FILE ATTACHMENT</option>
<option value="698">ADD PAYMENT PLAN NOTE</option>
<option value="700">ADD PAYMENT PLAN SIGNATURE</option>
<option value="505" selected="">ADD PROGRAM TO CLIENT-EMPLOYEE ASSIGNMENT</option>
<option value="388">ADD PROV PORTAL AGREEMENT HL7OwnerID -1 to 261</option>
<option value="510">ADD PROV PORTAL AGREEMENT HL7OwnerID 142 to 212</option>
<option value="389">ADD PROV PORTAL AGREEMENT HL7OwnerID 1668 to 27</option>
<option value="390">ADD PROV PORTAL AGREEMENT HL7OwnerID 1669 to 27</option>
<option value="391">ADD PROV PORTAL AGREEMENT HL7OwnerID 167 to 255</option>
<option value="446">ADD PROV PORTAL AGREEMENT HL7OwnerID 212 to 292</option>
<option value="527">ADD PROV PORTAL AGREEMENT HL7OwnerID 212 to 387</option>
<option value="392">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1667</option>
<option value="393">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1715</option>
<option value="394">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1716</option>
<option value="395">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1717</option>
<option value="396">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1718</option>
<option value="397">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1980</option>
<option value="398">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1983</option>
<option value="399">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1986</option>
<option value="400">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1987</option>
<option value="401">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1988</option>
<option value="402">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 1989</option>
<option value="403">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 2023</option>
<option value="404">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 2025</option>
<option value="405">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 2026</option>
<option value="406">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 2065</option>
<option value="407">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 2066</option>
<option value="408">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 2067</option>
<option value="409">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 31</option>
<option value="410">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 63</option>
<option value="411">ADD PROV PORTAL AGREEMENT HL7OwnerID 27 to 64</option>
<option value="412">ADD PROV PORTAL AGREEMENT HL7OwnerID 31 to 27</option>
<option value="413">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 243</option>
<option value="414">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 244</option>
<option value="415">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 249</option>
<option value="416">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 250</option>
<option value="417">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 251</option>
<option value="418">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 252</option>
<option value="419">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 253</option>
<option value="420">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 254</option>
<option value="421">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 259</option>
<option value="422">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 265</option>
<option value="423">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 275</option>
<option value="424">ADD PROV PORTAL AGREEMENT HL7OwnerID 53 to 276</option>
<option value="425">ADD PROV PORTAL AGREEMENT HL7OwnerID 63 to 27</option>
<option value="426">ADD PROV PORTAL AGREEMENT HL7OwnerID 64 to 27</option>
<option value="273">ADD PROV PORTAL AGREEMENT PARTNER ID 1 TO 1</option>
<option value="274">ADD PROV PORTAL AGREEMENT PARTNER ID 1 TO 77</option>
<option value="275">ADD PROV PORTAL AGREEMENT PARTNER ID 1 TO 99</option>
<option value="427">ADD PROV PORTAL AGREEMENT PARTNER ID 1001 to 987</option>
<option value="428">ADD PROV PORTAL AGREEMENT PARTNER ID 146 to 987</option>
<option value="429">ADD PROV PORTAL AGREEMENT PARTNER ID 163 to 987</option>
<option value="430">ADD PROV PORTAL AGREEMENT PARTNER ID 397 to 987</option>
<option value="276">ADD PROV PORTAL AGREEMENT PARTNER ID 77 TO 1</option>
<option value="431">ADD PROV PORTAL AGREEMENT PARTNER ID 848 to 987</option>
<option value="277">ADD PROV PORTAL AGREEMENT PARTNER ID 88 TO 1</option>
<option value="432">ADD PROV PORTAL AGREEMENT PARTNER ID 966 to 987</option>
<option value="433">ADD PROV PORTAL AGREEMENT PARTNER ID 987 to 847</option>
<option value="278">ADD PROV PORTAL AGREEMENT PARTNER ID 99 TO 1</option>
<option value="355">ADD SCHEDULE PAGE</option>
<option value="201">ADMINISTER CLIENT MEDICATION</option>
<option value="513">ADVANCED AUTHENTICATION ACTIVATED</option>
<option value="511">ADVANCED AUTHENTICATION DEACTIVATED</option>
<option value="339">ANONYMOUS CLIENT CREATED</option>
<option value="352">ANONYMOUS CLIENT DELETED</option>
<option value="340">ANONYMOUS CLIENT EMPLOYEES MANAGED</option>
<option value="624">APPROVE CLIENT CREDIBLE PLAN</option>
<option value="543">APPROVE CLIENT PORTAL VISIT</option>
<option value="279">APPROVE CLIENT PRESCRIPTION</option>
<option value="42">APPROVE CLIENT VISIT</option>
<option value="81">APPROVE EMPLOYEE FORM</option>
<option value="258">ASSIGN ADJUSTMENT TYPE APPROVAL ROLE ORDER</option>
<option value="108">ASSIGN CLIENT CASE MANAGER</option>
<option value="74">ASSIGN CLIENT EMPLOYEE</option>
<option value="159">ASSIGN CLIENT GEOAREAS</option>
<option value="75">ASSIGN CLIENT PRIMARY EMPLOYEE</option>
<option value="469">ASSIGN CLIENT PRIMARY PHARMACY</option>
<option value="637">ASSIGN CLIENT PRIMARY PHYSICIAN</option>
<option value="54">ASSIGN CLIENT PROGRAM</option>
<option value="148">ASSIGN CLIENT SCHEDULE GROUP</option>
<option value="56">ASSIGN CLIENT TEAM</option>
<option value="688">ASSIGN CLIENT TO PAYMENT PLAN</option>
<option value="116">ASSIGN CREDENTIALS</option>
<option value="616">ASSIGN CREDIBLE PLAN TEMPLATE TO EMPLOYEE</option>
<option value="259">ASSIGN EMPLOYEE APPROVAL ROLE</option>
<option value="260">ASSIGN EMPLOYEE BILLING GROUPS</option>
<option value="160">ASSIGN EMPLOYEE GEOAREAS</option>
<option value="55">ASSIGN EMPLOYEE PROGRAM</option>
<option value="500">ASSIGN EMPLOYEE STANDING ORDER SET</option>
<option value="57">ASSIGN EMPLOYEE TEAM</option>
<option value="570">ASSIGN EXPORT TO WS USER</option>
<option value="502">ASSIGN TEAM STANDING ORDER SET</option>
<option value="261">ASSIGN VISIT APPROVAL ROLE ORDER</option>
<option value="135">AUTH RELEASE</option>
<option value="648">AUTO DELETE USER</option>
<option value="141">AUTO LOGIN</option>
<option value="214">BED BOARD DELETE</option>
<option value="215">BED BOARD INSERT</option>
<option value="474">BED BOARD INTERVAL ADD</option>
<option value="216">BED BOARD INTERVAL DELETE</option>
<option value="472">BED BOARD INTERVAL ENDED</option>
<option value="471">BED BOARD INTERVAL ENDED RIS</option>
<option value="217">BED BOARD INTERVAL INSERT</option>
<option value="470">BED BOARD INTERVAL INSERT RIS</option>
<option value="475">BED BOARD INTERVAL REACTIVATE</option>
<option value="473">BED BOARD INTERVAL RELEASED</option>
<option value="218">BED BOARD INTERVAL UPDATE</option>
<option value="219">BED BOARD UPDATE</option>
<option value="220">BI LOGON</option>
<option value="529">CANCEL EPA</option>
<option value="479">CARE APP PAGE DISPLAY</option>
<option value="385">CDN DISABLED ON LOGIN</option>
<option value="296">CHANGE ASSIGNED PHYSICIAN</option>
<option value="294">CHANGE INS (SWITCH)</option>
<option value="297">CHANGE INS (SWITCH) - Force Primary</option>
<option value="434">CHANGE INS (SWITCH) - MISSING PRIMARY</option>
<option value="514">CHANGE PASSWORD PROCESS COMPLETED</option>
<option value="506">CHANGE PROGRAM ON CLIENT-EMPLOYEE ASSIGNMENT</option>
<option value="435">Client Amendment Added</option>
<option value="436">Client Amendment Deleted</option>
<option value="437">Client Amendment Edited</option>
<option value="482">CLIENT DIAGNOSIS DIAGNOSIS SEQUENCE REVISITED</option>
<option value="491">CLIENT DIAGNOSIS FROM MULTI-AXIAL TO PROBLEM LIST</option>
<option value="478">CLIENT DIAGNOSIS MULTIAXIAL RESEQUENCED</option>
<option value="477">CLIENT DIAGNOSIS MULTIAXIAL RESET</option>
<option value="481">CLIENT DIAGNOSIS PROBLEM LIST RESEQUENCED</option>
<option value="671">CLIENT EDUCATION PRINTED</option>
<option value="669">CLIENT EDUCATION PUSHED TO PORTAL</option>
<option value="670">CLIENT EDUCATION SENT TO FRONT DESK</option>
<option value="143">CLIENT EPISODE AUTOMATICALLY INSERTED</option>
<option value="144">CLIENT EPISODE AUTOMATICALLY UPDATED</option>
<option value="504">CLIENT LAB RESULT SET AS UNMATCHED</option>
<option value="302">CLIENT LIABILITY SIGNATURE (CLNT AND EMP)</option>
<option value="641">CLIENT LINK ACCESSED</option>
<option value="638">CLIENT LINK ADDED</option>
<option value="639">CLIENT LINK DELETED</option>
<option value="640">CLIENT LINK UPDATED</option>
<option value="175">CLIENT NOTE DELETED</option>
<option value="176">CLIENT NOTE INSERTED</option>
<option value="208">CLIENT SUMMARY GENERATED</option>
<option value="209">CLIENT SUMMARY IMPORTED</option>
<option value="221">CLIENT VISIT FAXED</option>
<option value="222">CLIENT VISIT TEMPLATE FAXED</option>
<option value="531">CLINIC ADDED</option>
<option value="533">CLINIC STATUS UPDATED</option>
<option value="532">CLINIC UPDATED</option>
<option value="518">CLINICAL SUMMARY DOWNLOADED (CLIENT)</option>
<option value="438">CLINICAL SUMMARY GENERATED</option>
<option value="439">CLINICAL SUMMARY IMPORTED</option>
<option value="516">CLINICAL SUMMARY RECEIVED VIA DIRECT</option>
<option value="520">CLINICAL SUMMARY VIA DIRECT FAILED</option>
<option value="177">CLINICAL SUPPORT ACCEPTED</option>
<option value="178">CLINICAL SUPPORT CREATE</option>
<option value="440">CLINICAL SUPPORT CREATE - TEST</option>
<option value="441">CLINICAL SUPPORT CREATE TEST</option>
<option value="179">CLINICAL SUPPORT DELETED - DIAGNOSIS REMOVED</option>
<option value="180">CLINICAL SUPPORT DELETED - MED REMOVED</option>
<option value="181">CLINICAL SUPPORT PUSHED TO PORTAL</option>
<option value="182">CLINICAL SUPPORT REJECTED</option>
<option value="183">CLINICAL SUPPORT REMOVE ACCEPTANCE</option>
<option value="184">CLINICAL SUPPORT REMOVE REJECTED</option>
<option value="185">CLINICAL SUPPORT REMOVED FROM PORTAL</option>
<option value="332">CLONE CLIENT AUTHORIZATION</option>
<option value="625">CLONE CLIENT CREDIBLE PLAN</option>
<option value="333">CLONE CLIENT VISIT</option>
<option value="494">CLONED WHODAS ASSESSMENT SCORES</option>
<option value="484">COMPLETE PHYSICIAN ORDER LINE</option>
<option value="723">COPY CLIENT CREDIBLE PLAN</option>
<option value="653">CREATE CLIENT PORTAL CLIENT ACCESS KEY</option>
<option value="633">CREATE ENROLLMENT BATCH</option>
<option value="136">DECLINE REFILL REQUEST</option>
<option value="540">DEFAULT PRESCRIBER CLINIC SET</option>
<option value="587">DELETE 277</option>
<option value="581">DELETE 999 ACKNOWLEDGMENT FILE</option>
<option value="442">DELETE AMENDMENT</option>
<option value="684">DELETE BILLING PAYER CONTRACT</option>
<option value="678">DELETE BILLING PAYER FILE ATTACHMENT</option>
<option value="681">DELETE BILLING PAYER NOTE</option>
<option value="94">DELETE CLIENT ALLERGY</option>
<option value="29">DELETE CLIENT AUTHORIZATION</option>
<option value="30">DELETE CLIENT CONTACT</option>
<option value="622">DELETE CLIENT CREDIBLE PLAN</option>
<option value="31">DELETE CLIENT DEPENDENT</option>
<option value="281">DELETE CLIENT DIAGNOSIS</option>
<option value="632">DELETE CLIENT ENROLLMENT</option>
<option value="65">DELETE CLIENT EPISODE RECORD</option>
<option value="161">DELETE CLIENT EXTERNAL PROVIDER</option>
<option value="32">DELETE CLIENT FILE ATTACHMENT</option>
<option value="292">DELETE CLIENT IMMUNIZATION</option>
<option value="645">DELETE CLIENT IMPLANTABLE DEVICE</option>
<option value="28">DELETE CLIENT INSURANCE</option>
<option value="564">DELETE CLIENT LIABILITY FILE ATTACHMENT</option>
<option value="316">DELETE CLIENT MEDICAL PROFILE</option>
<option value="210">DELETE CLIENT MEDICAL PROFILE IMMUNIZATION</option>
<option value="27">DELETE CLIENT MEDICATION</option>
<option value="453">DELETE CLIENT PAYMENT</option>
<option value="691">DELETE CLIENT PAYMENT PLAN</option>
<option value="25">DELETE CLIENT RECORD</option>
<option value="26">DELETE CLIENT TXPLAN</option>
<option value="236">DELETE CLIENT TXPLUS</option>
<option value="171">DELETE CLIENT USER</option>
<option value="48">DELETE CLIENT VISIT RECORD</option>
<option value="33">DELETE CLIENT WARNING</option>
<option value="186">DELETE CLINICAL SUPPORT FILE ATTACHMENT</option>
<option value="467">DELETE CONDITION CODE</option>
<option value="604">DELETE CREDIBLE PLAN CUSTOM ELEMENT</option>
<option value="606">DELETE CREDIBLE PLAN DISCIPLINE</option>
<option value="598">DELETE CREDIBLE PLAN ELEMENT LOOKUP</option>
<option value="601">DELETE CREDIBLE PLAN EXTENDED FIELD</option>
<option value="592">DELETE CREDIBLE PLAN GOAL ACHIEVEMENT STATUS</option>
<option value="595">DELETE CREDIBLE PLAN PRIORITY LEVEL</option>
<option value="609">DELETE CREDIBLE PLAN RULE SET</option>
<option value="615">DELETE CREDIBLE PLAN TEMPLATE</option>
<option value="612">DELETE CREDIBLE PLAN TYPE</option>
<option value="187">DELETE EMPLOYEE FILE ATTACHMENT</option>
<option value="720">DELETE EMPLOYEE FORM FILE ATTACHMENT</option>
<option value="117">DELETE EMPLOYEE FORM RECORD</option>
<option value="67">DELETE EMPLOYEE PLANNER BLOCK</option>
<option value="66">DELETE EMPLOYEE PLANNER ITEM</option>
<option value="53">DELETE EMPLOYEE RECORD</option>
<option value="634">DELETE ENROLLMENT BATCH</option>
<option value="566">DELETE EXPORT WS USER</option>
<option value="443">DELETE IMMUNIZATIONS</option>
<option value="667">DELETE LINKED ACCOUNT</option>
<option value="458">DELETE OCCURRENCE CODE</option>
<option value="461">DELETE OCCURRENCE SPAN CODE</option>
<option value="694">DELETE PAYMENT PLAN FILE ATTACHMENT</option>
<option value="699">DELETE PAYMENT PLAN NOTE</option>
<option value="702">DELETE PAYMENT PLAN SIGNATURE</option>
<option value="483">DELETE PHYSICIAN ORDER LINE</option>
<option value="114">DELETE PLANNER BLOCK</option>
<option value="118">DELETE PLANNER BLOCK RECURRENCE</option>
<option value="103">DELETE PLANNER ITEM</option>
<option value="104">DELETE RESOURCE PLANNER BLOCK</option>
<option value="384">DELETE TXPLUS EXTENDED FIELD</option>
<option value="237">DELETE TXPLUS GOAL</option>
<option value="238">DELETE TXPLUS INTERVENTION</option>
<option value="239">DELETE TXPLUS OBJECT</option>
<option value="240">DELETE TXPLUS OBJECTIVE</option>
<option value="241">DELETE TXPLUS PROBLEM</option>
<option value="454">DELETE UNMATCHED LAB RESULT</option>
<option value="52">DELETE USER</option>
<option value="464">DELETE VALUE CODE</option>
<option value="188">DELETE VISIT FILE ATTACHMENT</option>
<option value="663">DENY CLIENT PRESCRIPTION CHANGE REQUEST(G)</option>
<option value="664">DENY CLIENT PRESCRIPTION CHANGE REQUEST(P)</option>
<option value="662">DENY CLIENT PRESCRIPTION CHANGE REQUEST(T)</option>
<option value="495">DIAGNOSIS RECORDS CODED TO ICD-10 (AXIS 1)</option>
<option value="496">DIAGNOSIS RECORDS CODED TO ICD-10 (AXIS 2)</option>
<option value="497">DIAGNOSIS RECORDS CODED TO ICD-10 (AXIS 3)</option>
<option value="654">DISABLE CLIENT PORTAL CLIENT ACCESS KEY</option>
<option value="119">DISCONTINUE CLIENT MEDICATION</option>
<option value="124">DISCONTINUE CLIENT PRESCRIPTION</option>
<option value="486">DISCONTINUE PHYSICIAN ORDER LINE</option>
<option value="557">EDIT DEA NUMBER</option>
<option value="704">ELABS ORDER CREATED</option>
<option value="706">ELABS ORDER DELETED</option>
<option value="707">ELABS ORDER EDITED</option>
<option value="710">ELABS ORDER SENT BY DIRECT MESSAGE</option>
<option value="709">ELABS ORDER SENT BY FAX</option>
<option value="708">ELABS ORDER SIGNED</option>
<option value="705">ELABS ORDER VIEWED</option>
<option value="716">ELABS RESULTS EDITED</option>
<option value="711">ELABS RESULTS ENTERED</option>
<option value="719">ELABS RESULTS IMPORTED</option>
<option value="713">ELABS RESULTS PRINTED</option>
<option value="715">ELABS RESULTS SENT BY DIRECT MESSAGE</option>
<option value="714">ELABS RESULTS SENT BY FAX</option>
<option value="480">eLABS RESULTS SIGNED</option>
<option value="712">ELABS RESULTS VIEWED</option>
<option value="718">ELABS UNASSIGN FROM CLIENT</option>
<option value="717">ELABS UNMATCHED ASSIGNED TO CLIENT</option>
<option value="450">ELECTRONIC ERROR PRESCRIPTION</option>
<option value="109">ELECTRONIC FAIL PRESCRIPTION</option>
<option value="369">ELECTRONIC FAIL PRESCRIPTION CANCEL</option>
<option value="370">ELECTRONIC SUCCESS PRESCRIPTION CANCEL</option>
<option value="202">EMAR GROUP DELETED</option>
<option value="189">EMERGENCY CLIENT ASSIGNMENT</option>
<option value="190">EMPLOYEE NOTE DELETED</option>
<option value="191">EMPLOYEE NOTE INSERTED</option>
<option value="655">ENABLE CLIENT PORTAL CLIENT ACCESS KEY</option>
<option value="545">EPCS ADD DEA-REGISTERED EPCS ADMIN</option>
<option value="547">EPCS ADD NON-DEA EPCS ADMIN</option>
<option value="552">EPCS CANCEL REVOCATION OF EPCS RIGHTS</option>
<option value="551">EPCS DENY REQUEST OF EPCS RIGHTS</option>
<option value="559">EPCS EXOSTAR TFA FAIL FOR DIGITAL SIGNING</option>
<option value="558">EPCS EXOSTAR TFA SUCCESS FOR DIGITAL SIGNING</option>
<option value="544">EPCS PRESCRIPTION PRINT</option>
<option value="546">EPCS REMOVE DEA-REGISTERED EPCS ADMIN</option>
<option value="548">EPCS REMOVE NON-DEA EPCS ADMIN</option>
<option value="549">EPCS REQUEST EPCS RIGHTS</option>
<option value="550">EPCS REQUEST REVOCATION OF EPCS RIGHTS</option>
<option value="556">EPCS RIGHTS CONFIRM REQUEST EXOSTAR TFA FAIL</option>
<option value="555">EPCS RIGHTS CONFIRM REQUEST EXOSTAR TFA SUCCESS</option>
<option value="554">EPCS RIGHTS CONFIRM REVOCATION EXOSTAR TFA FAIL</option>
<option value="553">EPCS RIGHTS CONFIRM REVOCATION EXOSTAR TFA SUCCESS</option>
<option value="561">EPCS SERVICE LEVEL OFF</option>
<option value="560">EPCS SERVICE LEVEL ON</option>
<option value="651">EXOSTAR ID PROOFING STATUS RESET</option>
<option value="673">EXOSTAR ID PROOFING SUBSCRIPTION RENEWAL FAILURE</option>
<option value="672">EXOSTAR ID PROOFING SUBSCRIPTION RENEWAL SUCCESS</option>
<option value="326">EXPORT CLIENT CONTACTS</option>
<option value="327">EXPORT CLIENT FAMILY</option>
<option value="697">EXPORT PAYMENT PLAN LIST</option>
<option value="374">EXT CARE PROVIDER TEMPLATE</option>
<option value="149">FAX FAIL PRESCRIPTION</option>
<option value="509">FORCE VISIT EPISODE</option>
<option value="192">FORGOT PASSWORD PROCESS COMPLETED</option>
<option value="193">FORGOT PASSWORD PROCESS STARTED</option>
<option value="623">GENERATE CLIENT CREDIBLE PLAN HL7 FILE</option>
<option value="194">INCOMPLETE CLIENT VISIT DELETED</option>
<option value="195">INCOMPLETE CLIENT VISIT INSERTED</option>
<option value="98">INCOMPLETE CLIENT VISIT OPENED</option>
<option value="242">INCOMPLETE EMPLOYEE VISIT INSERTED</option>
<option value="528">INITIATE EPA</option>
<option value="367">INSERT</option>
<option value="586">INSERT 277</option>
<option value="444">INSERT AMENDMENT</option>
<option value="318">INSERT ATTENDANCE GROUP</option>
<option value="95">INSERT CLIENT ALLERGY</option>
<option value="10">INSERT CLIENT AUTHORIZATION</option>
<option value="70">INSERT CLIENT AUTHORIZATION LEVEL</option>
<option value="11">INSERT CLIENT CONTACT</option>
<option value="12">INSERT CLIENT DEPENDENT</option>
<option value="8">INSERT CLIENT DIAGNOSIS</option>
<option value="476">INSERT CLIENT DIAGNOSIS AS MULTI-AXIAL</option>
<option value="492">INSERT CLIENT DIAGNOSIS AS PROBLEM LIST</option>
<option value="147">INSERT CLIENT EPISODE</option>
<option value="150">INSERT CLIENT EPISODE (AUTO)</option>
<option value="145">INSERT CLIENT EPISODE(AUTO)</option>
<option value="162">INSERT CLIENT EXTERNAL PROVIDER</option>
<option value="13">INSERT CLIENT FILE ATTACHMENT</option>
<option value="293">INSERT CLIENT IMMUNIZATION</option>
<option value="644">INSERT CLIENT IMPLANTABLE DEVICE</option>
<option value="9">INSERT CLIENT INSURANCE</option>
<option value="562">INSERT CLIENT LIABILITY FILE ATTACHMENT</option>
<option value="211">INSERT CLIENT MEDICAL PROFILE</option>
<option value="7">INSERT CLIENT MEDICATION</option>
<option value="125">INSERT CLIENT MEDICATION REFILL</option>
<option value="120">INSERT CLIENT MEDICATION RX</option>
<option value="163">INSERT CLIENT MEDICATION RX THROUGH NONSPI</option>
<option value="164">INSERT CLIENT MEDICATION THROUGH NONSPI</option>
<option value="282">INSERT CLIENT PORTAL FILE ATTACHMENT</option>
<option value="5">INSERT CLIENT RECORD</option>
<option value="6">INSERT CLIENT TXPLAN</option>
<option value="68">INSERT CLIENT TXPLAN FROM FORM</option>
<option value="243">INSERT CLIENT TXPLUS</option>
<option value="172">INSERT CLIENT USER</option>
<option value="39">INSERT CLIENT VISIT DATAENTRY</option>
<option value="346">Insert Client Visit Form Txplus Goal</option>
<option value="348">Insert Client Visit Form Txplus Intervention</option>
<option value="347">Insert Client Visit Form Txplus Objective</option>
<option value="345">Insert Client Visit Form Txplus Problem</option>
<option value="37">INSERT CLIENT VISIT HANDHELD</option>
<option value="303">INSERT CLIENT VISIT VIA INBOUND WEBSERVICE</option>
<option value="38">INSERT CLIENT VISIT WEBFORMS</option>
<option value="14">INSERT CLIENT WARNING</option>
<option value="203">INSERT CLINICAL SUPPORT FILE ATTACHMENT</option>
<option value="466">INSERT CONDITION CODE</option>
<option value="196">INSERT EMPLOYEE FILE ATTACHMENT</option>
<option value="82">INSERT EMPLOYEE FORM FILE ATTACHMENT</option>
<option value="49">INSERT EMPLOYEE RECORD</option>
<option value="71">INSERT EMPLOYEE WEBFORM</option>
<option value="83">INSERT EMPLOYEE WEBFORMS</option>
<option value="567">INSERT EXPORT WS USER</option>
<option value="372">INSERT IMMUNIZATIONS</option>
<option value="305">INSERT INACTIVE TXPLUS GOAL</option>
<option value="308">INSERT INACTIVE TXPLUS INTERVENTION</option>
<option value="311">INSERT INACTIVE TXPLUS OBJECTIVE</option>
<option value="314">INSERT INACTIVE TXPLUS PROBLEM</option>
<option value="110">INSERT NEW PRESCRIPTION</option>
<option value="457">INSERT OCCURRENCE CODE</option>
<option value="460">INSERT OCCURRENCE SPAN CODE</option>
<option value="151">INSERT PHYSICIAN ORDER LINE</option>
<option value="649">INSERT PLANNER BLOCK</option>
<option value="650">INSERT PLANNER BLOCK RECURRENCE</option>
<option value="262">INSERT RESOURCE PLANNER BLOCK</option>
<option value="96">INSERT SCHEDULE ENTRY</option>
<option value="383">INSERT TXPLUS EXTENDED FIELD</option>
<option value="244">INSERT TXPLUS GOAL</option>
<option value="245">INSERT TXPLUS INTERVENTION</option>
<option value="246">INSERT TXPLUS OBJECTIVE</option>
<option value="247">INSERT TXPLUS PROBLEM</option>
<option value="647">INSERT USER PROFILE</option>
<option value="463">INSERT VALUE CODE</option>
<option value="197">INSERT VISIT FILE ATTACHMENT</option>
<option value="223">MEDICATION ADMIN RECORD INSERTED</option>
<option value="248">MEDICATION ADMIN RECORD RECONCILED</option>
<option value="224">MEDICATION ADMIN RECORD REMOVED</option>
<option value="225">MEDICATION ADMIN RECORD UPDATED</option>
<option value="226">MEDICATION ADMINISTERED INSERTED</option>
<option value="227">MEDICATION ELIGIBILITY FAILED</option>
<option value="456">MEDICATION ELIGIBILITY NOT AVAILABLE</option>
<option value="228">MEDICATION ELIGIBILITY UPDATED</option>
<option value="249">MEDICATION NOTE UPDATED</option>
<option value="229">MEDICATION SCHEDULE DISCONTINUED</option>
<option value="230">MEDICATION SCHEDULE INSERTED</option>
<option value="231">MEDICATION SCHEDULE UPDATED</option>
<option value="206">MERGE CLIENT DUPLICATE</option>
<option value="263">MESSAGE HUB DISMISSAL</option>
<option value="488">NEW CLIENT DIAGNOSIS BY APPLYING VISIT</option>
<option value="487">NEW CLIENT DIAGNOSIS BY APPLYING VISIT DIFF FORMAT</option>
<option value="232">PBM MEDICATION HISTORY FAILED</option>
<option value="455">PBM MEDICATION HISTORY NOT AVAILABLE</option>
<option value="233">PBM MEDICATION HISTORY UPDATE</option>
<option value="234">PBM MEDICATION HISTORY UPDATED</option>
<option value="250">PILLBOX CLOSED</option>
<option value="251">PILLBOX INSERTED</option>
<option value="252">PILLBOX UPDATED</option>
<option value="535">PRESCRIBER ADDED</option>
<option value="538">PRESCRIBER CLINIC ASSIGNED</option>
<option value="539">PRESCRIBER CLINIC UNASSIGNED</option>
<option value="534">PRESCRIBER CLINIC UPDATED</option>
<option value="537">PRESCRIBER STATUS UPDATED</option>
<option value="536">PRESCRIBER UPDATED</option>
<option value="325">PRINT CLIENT MEDICATIONS</option>
<option value="324">PRINT CLIENT PLANNER</option>
<option value="542">PRINT CLIENT PORTAL VISIT</option>
<option value="321">PRINT CLIENT PROFILE</option>
<option value="36">PRINT CLIENT VISIT</option>
<option value="290">PRINT CLIENT VISIT (PROV PORTAL)</option>
<option value="198">PRINT CLIENT VISIT SUMMARY</option>
<option value="626">PRINT CREDIBLE PLAN</option>
<option value="628">PRINT CREDIBLE PLAN - CLIENT PROFILE</option>
<option value="627">PRINT CREDIBLE PLAN HEADER</option>
<option value="629">PRINT CREDIBLE PLAN HEADER - CLIENT PROFILE</option>
<option value="84">PRINT EMPLOYEE FORM</option>
<option value="323">PRINT EMPLOYEE PLANNER</option>
<option value="329">PRINT LIABILITY BASIC</option>
<option value="336">PRINT LIABILITY FORM</option>
<option value="334">PRINT LIABILITY SCALE</option>
<option value="335">PRINT LIABILITY SLIDING FEE</option>
<option value="330">PRINT MEDICATION SCHEDULE</option>
<option value="328">PRINT PAYMENT RECEIPT</option>
<option value="111">PRINT PRESCRIPTION</option>
<option value="112">PRINT PRESCRIPTION COPY</option>
<option value="322">PRINT TXPLUS PLAN</option>
<option value="283">PROV PORTAL AGREEMENT TOGGLE (AS RECEIVER)</option>
<option value="284">PROV PORTAL AGREEMENT TOGGLE (AS SENDER)</option>
<option value="285">PURGE CLIENT RECORD(S)</option>
<option value="105">REASSIGNED SCHEDULE ENTRY</option>
<option value="264">RECEIVE CLIENT RECORD DATAEX</option>
<option value="291">RECEIVE EMPLOYEE Record DataEx</option>
<option value="126">REJECT CLIENT PRESCRIPTION</option>
<option value="286">REJECT PROV PORTAL AGREEMENT</option>
<option value="165">REMOVE CLIENT DUPLICATE</option>
<option value="265">REMOVE DEFAULT EMPLOYEE BILLING GROUPS</option>
<option value="287">REMOVE EMPLOYEE TIME ZONE</option>
<option value="507">REMOVE PROGRAM FROM CLIENT-EMPLOYEE ASSIGNMENT</option>
<option value="137">REMOVED NOTIFICATION TRIGGERS</option>
<option value="485">RENEW PHYSICIAN ORDER LINE</option>
<option value="146">REPROCESS CLIENT VISIT</option>
<option value="635">REQUEST REALTIME INSURANCE ELIGIBILITY</option>
<option value="106">RESCHEDULE SCHEDULE ENTRY</option>
<option value="498">RESIDENTIAL INPATIENT STAY INTERVAL RE-ACTIVATED</option>
<option value="523">REVENUE REPROCESS COMPLETED</option>
<option value="524">REVENUE REPROCESS ERROR</option>
<option value="522">REVENUE REPROCESS QUEUED</option>
<option value="521">REVENUE REPROCESS STARTED</option>
<option value="517">ROLLBACK CLIENT INSURANCE</option>
<option value="288">SCHEDULE CLIENT PURGE</option>
<option value="152">SELECT CLIENT AS PCP</option>
<option value="519">SEND CLINICAL SUMMARY VIA DIRECT</option>
<option value="489">SERIALIZED FORM QUESTION APPLIED:DX INSERTED</option>
<option value="490">SERIALIZED FORM QUESTION APPLIED:DX UPDATED</option>
<option value="266">SET DEFAULT EMPLOYEE BILLING GROUPS</option>
<option value="656">SHARE CLIENT PORTAL CLIENT ACCESS KEY</option>
<option value="267">SHARE CLIENT RECORD DATAEX</option>
<option value="268">SHARE EMPLOYEE RECORD DATAEX</option>
<option value="153">SIGN PHYSICIAN ORDER LINE</option>
<option value="508">SOS CONTRAINDICATION WARNING OVERRIDDEN</option>
<option value="269">SPLIT VISIT CHANGE</option>
<option value="674">SWITCH ACCOUNT - INBOUND</option>
<option value="668">SWITCH ACCOUNT - OUTBOUND</option>
<option value="675">SWITCH ACCOUNT ACCESSED</option>
<option value="207">SWITCHED ACTIVE CLIENT DIAGNOSIS</option>
<option value="199">TO DO LIST ITEM DELETED</option>
<option value="200">TO DO LIST ITEM INSERTED</option>
<option value="43">UNAPPROVE CLIENT VISIT</option>
<option value="85">UNAPPROVE EMPLOYEE FORM</option>
<option value="113">UNAPPROVE MULTI STAGE CLIENT VISIT</option>
<option value="272">UNASSIGN CLIENT CASE MANAGER</option>
<option value="76">UNASSIGN CLIENT EMPLOYEE</option>
<option value="689">UNASSIGN CLIENT FROM PAYMENT PLAN</option>
<option value="167">UNASSIGN CLIENT GEOAREAS</option>
<option value="121">UNASSIGN CLIENT PRIMARY EMPLOYEE</option>
<option value="526">UNASSIGN CLIENT PRIMARY PHYSICIAN</option>
<option value="58">UNASSIGN CLIENT PROGRAM</option>
<option value="154">UNASSIGN CLIENT SCHEDULE GROUP</option>
<option value="59">UNASSIGN CLIENT TEAM</option>
<option value="122">UNASSIGN CREDENTIALS</option>
<option value="617">UNASSIGN CREDIBLE PLAN TEMPLATE TO EMPLOYEE</option>
<option value="270">UNASSIGN EMPLOYEE APPROVAL ROLE</option>
<option value="271">UNASSIGN EMPLOYEE BILLING GROUP</option>
<option value="168">UNASSIGN EMPLOYEE GEOAREAS</option>
<option value="60">UNASSIGN EMPLOYEE PROGRAM</option>
<option value="501">UNASSIGN EMPLOYEE STANDING ORDER SET</option>
<option value="61">UNASSIGN EMPLOYEE TEAM</option>
<option value="571">UNASSIGN EXPORT TO WS USER</option>
<option value="503">UNASSIGN TEAM STANDING ORDER SET</option>
<option value="34">UNDELETE CLIENT RECORD</option>
<option value="138">UNDO AUTH RELEASE</option>
<option value="155">UNSELECT CLIENT AS PCP</option>
<option value="366">UPDATE</option>
<option value="588">UPDATE 277</option>
<option value="306">UPDATE ACTIVE TXPLUS GOAL</option>
<option value="309">UPDATE ACTIVE TXPLUS INTERVENTION</option>
<option value="312">UPDATE ACTIVE TXPLUS OBJECTIVE</option>
<option value="315">UPDATE ACTIVE TXPLUS PROBLEM</option>
<option value="445">UPDATE AMENDMENT</option>
<option value="317">UPDATE ATTENDANCE GROUP</option>
<option value="683">UPDATE BILLING PAYER CONTRACT</option>
<option value="677">UPDATE BILLING PAYER FILE ATTACHMENT</option>
<option value="97">UPDATE CLIENT ALLERGY</option>
<option value="21">UPDATE CLIENT AUTHORIZATION</option>
<option value="22">UPDATE CLIENT CONTACT</option>
<option value="621">UPDATE CLIENT CREDIBLE PLAN</option>
<option value="23">UPDATE CLIENT DEPENDENT</option>
<option value="19">UPDATE CLIENT DIAGNOSIS</option>
<option value="631">UPDATE CLIENT ENROLLMENT</option>
<option value="158">UPDATE CLIENT EPISODE (AUTO)</option>
<option value="88">UPDATE CLIENT EPISODE FROM FORM</option>
<option value="78">UPDATE CLIENT EPISODE RECORD</option>
<option value="169">UPDATE CLIENT EXTERNAL PROVIDER</option>
<option value="89">UPDATE CLIENT FROM FORM</option>
<option value="643">UPDATE CLIENT IMPLANTABLE DEVICE</option>
<option value="20">UPDATE CLIENT INSURANCE</option>
<option value="123">UPDATE CLIENT LIABILITY</option>
<option value="563">UPDATE CLIENT LIABILITY FILE ATTACHMENT</option>
<option value="298">UPDATE CLIENT LIABILITY SIGNATURE (CLIENT)</option>
<option value="301">UPDATE CLIENT LIABILITY SIGNATURE (CLNT AND EMP)</option>
<option value="300">UPDATE CLIENT LIABILITY SIGNATURE (EMPLOYEE)</option>
<option value="18">UPDATE CLIENT MED NOTES</option>
<option value="213">UPDATE CLIENT MEDICAL PROFILE</option>
<option value="17">UPDATE CLIENT MEDICATION</option>
<option value="690">UPDATE CLIENT PAYMENT PLAN</option>
<option value="15">UPDATE CLIENT RECORD</option>
<option value="16">UPDATE CLIENT TXPLAN</option>
<option value="69">UPDATE CLIENT TXPLAN FROM FORM</option>
<option value="253">UPDATE CLIENT TXPLUS</option>
<option value="173">UPDATE CLIENT USER</option>
<option value="174">UPDATE CLIENT USER PASSWORD</option>
<option value="44">UPDATE CLIENT VISIT ADD SIGNATURE</option>
<option value="499">UPDATE CLIENT VISIT DELETE CATEGORY SIGNATURE</option>
<option value="107">UPDATE CLIENT VISIT DELETE SIGNATURE</option>
<option value="41">UPDATE CLIENT VISIT FORM</option>
<option value="342">Update Client Visit Form Txplus Goal</option>
<option value="344">Update Client Visit Form Txplus Intervention</option>
<option value="343">Update Client Visit Form Txplus Objective</option>
<option value="341">Update Client Visit Form Txplus Problem</option>
<option value="45">UPDATE CLIENT VISIT LINK UNSCHEDULED</option>
<option value="40">UPDATE CLIENT VISIT RECORD</option>
<option value="46">UPDATE CLIENT VISIT RELINK CLIENT</option>
<option value="47">UPDATE CLIENT VISIT RELINK EMPLOYEE</option>
<option value="368">UPDATE CLIENT VISIT SAVED</option>
<option value="90">UPDATE CLIENT WARNING</option>
<option value="91">UPDATE CLIENTEXT FROM FORM</option>
<option value="24">UPDATE CLIENTEXT RECORD</option>
<option value="468">UPDATE CONDITION CODE</option>
<option value="299">UPDATE CREDENTIALS</option>
<option value="603">UPDATE CREDIBLE PLAN CUSTOM ELEMENT</option>
<option value="605">UPDATE CREDIBLE PLAN DISCIPLINE</option>
<option value="597">UPDATE CREDIBLE PLAN ELEMENT LOOKUP</option>
<option value="600">UPDATE CREDIBLE PLAN EXTENDED FIELD</option>
<option value="591">UPDATE CREDIBLE PLAN GOAL ACHIEVEMENT STATUS</option>
<option value="594">UPDATE CREDIBLE PLAN PRIORITY LEVEL</option>
<option value="608">UPDATE CREDIBLE PLAN RULE SET</option>
<option value="614">UPDATE CREDIBLE PLAN TEMPLATE</option>
<option value="611">UPDATE CREDIBLE PLAN TYPE</option>
<option value="86">UPDATE EMPLOYEE FORM ADD SIGNATURE</option>
<option value="87">UPDATE EMPLOYEE FORM RECORD</option>
<option value="92">UPDATE EMPLOYEE FROM FORM</option>
<option value="642">UPDATE EMPLOYEE PROFILE CODE</option>
<option value="50">UPDATE EMPLOYEE RECORD</option>
<option value="289">UPDATE EMPLOYEE TIME ZONE</option>
<option value="589">UPDATE EMPLOYEE VISIT FORM</option>
<option value="722">UPDATE EMPLOYEE VISIT RELINK BY EMPLOYEE</option>
<option value="170">UPDATE EMPLOYEE VISIT RELINK EMPLOYEE</option>
<option value="721">UPDATE EMPLOYEE VISIT RELINK FOR EMPLOYEE</option>
<option value="569">UPDATE EXPORT WS PASSWORD</option>
<option value="568">UPDATE EXPORT WS USER</option>
<option value="371">Update Extended Fields</option>
<option value="703">UPDATE FACILITY ASSIGNMENTS</option>
<option value="373">UPDATE IMMUNIZATIONS</option>
<option value="304">UPDATE INACTIVE TXPLUS GOAL</option>
<option value="307">UPDATE INACTIVE TXPLUS INTERVENTION</option>
<option value="310">UPDATE INACTIVE TXPLUS OBJECTIVE</option>
<option value="313">UPDATE INACTIVE TXPLUS PROBLEM</option>
<option value="666">UPDATE LINKED ACCOUNT</option>
<option value="459">UPDATE OCCURRENCE CODE</option>
<option value="462">UPDATE OCCURRENCE SPAN CODE</option>
<option value="693">UPDATE PAYMENT PLAN FILE ATTACHMENT</option>
<option value="701">UPDATE PAYMENT PLAN SIGNATURE</option>
<option value="156">UPDATE PHYSICIAN ORDER LINE</option>
<option value="139">UPDATE REFILL REQUEST</option>
<option value="157">UPDATE SCHEDULE ENTRY</option>
<option value="382">UPDATE TXPLUS EXTENDED FIELD</option>
<option value="254">UPDATE TXPLUS GOAL</option>
<option value="255">UPDATE TXPLUS INTERVENTION</option>
<option value="256">UPDATE TXPLUS OBJECTIVE</option>
<option value="257">UPDATE TXPLUS PROBLEM</option>
<option value="515">UPDATE TXPLUS TEMPLATE</option>
<option value="51">UPDATE USER</option>
<option value="73">UPDATE USER PASSWORD</option>
<option value="646">UPDATE USER PROFILE</option>
<option value="465">UPDATE VALUE CODE</option>
<option value="493">UPDATE WHODAS ASSESSMENT SCORES</option>
<option value="140">UPDATED CREDIBLE RX PRESCRIBER</option>
<option value="580">UPLOAD 999 ACKNOWLEDGMENT FILE</option>
<option value="679">VIEW BILLING PAYER FILE ATTACHMENT</option>
<option value="619">VIEW CLIENT CREDIBLE PLAN</option>
<option value="618">VIEW CLIENT CREDIBLE PLAN LIST</option>
<option value="565">VIEW CLIENT LIABILITY FILE ATTACHMENT</option>
<option value="686">VIEW CLIENT PAYMENT PLAN</option>
<option value="685">VIEW CLIENT PAYMENT PLAN LIST PAGE</option>
<option value="695">VIEW PAYMENT PLAN FILE ATTACHMENT</option>
<option value="696">VIEW PAYMENT PLAN LIST</option>
<option value="512">VIEWED CLIENT STATEMENT</option>
<option value="235">YOQ ACCESS THROUGH LINK</option>
</select>
'''


def correct():
    corrected = []
    admin_file_name = os.path.dirname(__file__)
    admin_directory = os.path.dirname(admin_file_name)
    schema_file_path = os.path.join(admin_directory, 'starters', 'change_types.json')
    schema = {}
    with open(schema_file_path) as test:
        test_schema = json.load(test)
        for entry in test_schema:
            schema[entry['change_action']] = entry
    soup = bs4.BeautifulSoup(test_html, features='html.parser')
    options = soup.find_all('option')

    for option in options:
        change_id = option.attrs.get('value')
        change_action = option.text
        if not change_id or not change_action:
            continue
        action_id = int(change_id)
        schema_entry = schema.get(change_action)
        if not schema_entry:
            continue
        schema_entry['action_id'] = action_id
        identifier_stem = IdentifierStem.from_raw(schema_entry['identifier_stem'])
        pairs = identifier_stem.paired_identifiers
        pairs['action_id'] = action_id
        corrected_stem = IdentifierStem('vertex', 'ChangeLogType', pairs)
        sid_value = corrected_stem.for_dynamo
        schema_entry['identifier_stem'] = str(corrected_stem)
        schema_entry['sid_value'] = sid_value
        corrected.append(schema_entry)
    string_corrected = json.dumps(corrected)
    print(string_corrected)


if __name__ == '__main__':
    correct()
